# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/glios',
                'doc_host': 'https://philhosophy.github.io',
                'git_url': 'https://github.com/philhosophy/glios',
                'lib_path': 'glios'},
  'syms': {'glios.core': {'glios.core.foo': ('core.html#foo', 'glios/core.py')}}}
